### PR TITLE
Update solidity contracts

### PR DESCRIPTION
**Pull request by njgheorghita**
Updated the solidity contracts to reflect the pending changes in https://github.com/ethereum/EIPs/pull/1609. Thought I'd share them here if you want to use these changes.

### CODE REVIEW

**Comment by njgheorghita** [comment]
Ping @gnidan @seesemichaelj for :eyes:.

**Review by gnidan — APPROVED** [review]

**Comment by njgheorghita** [comment]
@gnidan Thanks! I'm not quite sure why coveralls is failing? Any clues?

**Comment by seesemichaelj** [comment]
@njgheorghita I believe coveralls is set to fail if coverage decreases by at least 0.5%

**Comment by cgewecke** [comment]
Hi @njgheorghita :) 

It looks like only [happy-path cases](https://coveralls.io/builds/23311095/source?filename=contracts/PackageRegistry.sol#L307) are covered. There are no tests for what happens when the require statements in `PackageRegistry.getReleaseId` and `PackageRegistry.numReleaseIds` fail. The coverage tool treats those as conditional branches.

Think this should be looked at carefully. These are view functions and IIRC behavior of `require` in that context is weird. For example it's not clear we would get the expected result (0) from `PackageRegistry.numReleaseIds` if a package doesn't exist.

Is it possible the contracts should return 0 bytes for a non-existent releaseId as well?

**Comment by cgewecke** [comment]
@seesemichaelj If it's tolerant in that way it should be made more fanatical. 

I think most [production Solidity projects](https://github.com/aragon/aragonOS) try to get 100% line and branch coverage but we have some untested things and conditions that can't be falsified here. See #12 (which might be out of date)

**Comment by cgewecke** [comment]
@njgheorghita nice, LGTM

**Comment by njgheorghita** [comment]
Thanks @seesemichaelj! Not sure about changing the threshold as it seemed it did its job here.

Hey @cgewecke - Nailed it! I updated `getReleaseId` and `numReleaseIds` to explicitly return `0` if the release doesn't exist.

**Pull request merged**
